Bug 1677419 - Token cancellation and verification should take an extra step to confirm
mozilla-bteam/bmo pull request #1661
Opened 2020-11-17 17:32 UTC by dklawren

2020-11-18 04:36 UTC, globau requested changes
This looks good, but only covers the cancellation case.

2020-11-18 14:27 UTC, dklawren commented
Ah right. It was in my head that people were mostly complaining about Outlook, etc. visiting the cancellation link when they wanted to accept the change instead. I will update to add a confirmation page for accepting the change as well.

2020-11-25 21:17 UTC, dklawren commented
> This looks good, but only covers the cancellation case.

Actually looking into this more, you do not need the confirmation page for 'confirming the email change' as the user already gets a form where they have to enter the old email address before the change is actually made. So we should be good with the current code.

2020-11-30 15:43 UTC, globau approved these changes

2020-11-30 15:43 UTC, merged