Bug 1690203 - Automatically set priority to P1 when severity is set to S1
mozilla-bteam/bmo pull request #1715
Opened 2021-05-13 16:51 UTC by dklawren

2021-05-17 05:09 UTC, globau requested changes
The follow item from the spec has not been implemented:
- set a tooltip explaining that the field value is locked due to the severity

2021-05-17 05:09 UTC, globau commented on extensions/MozChangeField/template/en/default/hook/bug_modal/header-end.html.tmpl
> +[% javascript_urls.push("extensions/MozChangeField/web/js/severitys1priorityp1.js") %]
That filename looks like soup, `severity-s1-priority-p1.js` would be much easier to read.

2021-05-17 05:09 UTC, globau commented on extensions/MozChangeField/lib/Post/SeverityS1PriorityP1.pm
> +    @{get_legal_field_values('priority')})
`grep` in a boolean context is inefficient; use `any` (see `PerlCritic/ProhibitBooleanGrep`)

2021-05-18 20:30 UTC, dklawren commented on extensions/MozChangeField/web/js/severitys1priorityp1.js
> +      this.severity.addEventListener("change", () => this.severity_onselect());
Tried that initially and did not work as 'this' is not bound properly. Using => style functions explicitly binds 'this' based on context and worked properly.

2021-05-19 06:37 UTC, globau approved these changes

2021-05-21 14:31 UTC, merged