Bug 1721056 - 404 error link to "bug writing guidelines" on top of enter_bug.cgi
mozilla-bteam/bmo pull request #1738
Opened 2021-07-21 01:49 UTC by dklawren

2021-07-21 14:30 UTC, globau requested changes

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +    use one of the available <a href="http://www.mozilla.org/support/">support options</a>.</strong>
this should be https

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +    Do not edit this page!</p>
This sentence should be removed.

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +   your [% terms.bug %] has already been fixed (e.g. <a href="http://www.mozilla.com/en-US/firefox/channel/">
https here too

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +   Firefox Beta, Aurora</a>, or bleeding-edge <a class="link-https" href="https://nightly.mozilla.org/">
Aurora doesn't exist.

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +   <a href="https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles">
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +       on <a href="/en-US/docs/Screening_duplicate_bugs">screening duplicate [% terms.bugs %]</a>).</li>
broken link

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  <a href="/en-US/docs/Mozilla/Performance/about:memory">attach the output of about:memory</a>.
broken link

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  <a href="https://support.mozilla.org/en-US/kb/firefox-uses-too-much-memory-ram">Firefox Uses Too Much
https://support.mozilla.org/en-US/kb/firefox-uses-too-much-memory-or-cpu-resources

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  <a href="/en-US/docs/Mozilla/Performance/Reporting_a_Performance_Problem">provide a link to the
broken link

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  please follow the instructions in <a href="/en-US/docs/How_to_Report_a_Hung_Firefox">How to Report a
broken link

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  <a href="/en-US/docs/Reducing_testcases">reduced testcase</a> and attach it to the [% terms.bug %] report.
broken link

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +  <a href="http://mozilla.github.io/mozregression/quickstart.html">regression window</a> can help identify
https

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +<p><a href="http://www.chiark.greenend.org.uk/~sgtatham/bugs.html#intermittent">What if my [% terms.bug %] seems
https

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +        <a href="https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles">
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

2021-07-21 14:30 UTC, globau commented on extensions/BMO/template/en/default/pages/bug-writing.html.tmpl
> +    1) View any web page. (I used the default sample page, http://www.google.com/).<br>
https

2021-07-21 14:32 UTC, dklawren commented
Thanks for the review. Anything that is broken markup was broken before on the original page. Will fix the issues.

2021-07-21 14:34 UTC, globau commented
> Thanks for the review. Anything that is broken markup was broken before on the original page. Will fix the issues.

We can't pull in content without ensuring it's accurate and all links work.

2021-07-22 14:12 UTC, globau approved these changes

2021-07-22 14:28 UTC, merged