Bug 1628759 - Hide bugs in See Also fields from users without access
mozilla-bteam/bmo pull request #1782
Opened 2021-11-23 16:18 UTC by dklawren

2021-11-24 03:04 UTC, dklawren commented
Not yet ready for review. Want to do some more testing.

2021-11-24 20:37 UTC, dklawren commented
Ok ready for review. Verified that someone with out permission to see the bug referred to cannot remove the reference.

2021-11-25 06:55 UTC, globau requested changes
Users should be prevented from adding or removing bugs they cannot see to/from see-also, both via the API and at bug creation time.

2021-11-25 06:55 UTC, globau commented on qa/t/webservice_bug_get_bugs.t
> +
I'd like to see a few more tests here to cover the whole matrix: public/public, public/private, private/public, and private/private

2021-11-25 06:55 UTC, globau commented on qa/t/webservice_bug_get.t
> +
I'd like to see a few more tests here to cover the whole matrix: public/public, public/private, private/public, and private/private

2021-12-17 05:27 UTC, globau approved these changes

2021-12-17 18:04 UTC, merged