Bug 1742725 - Add an option to disable "attach pasted text" feature
mozilla-bteam/bmo pull request #1783
Opened 2021-11-24 00:14 UTC by arai-a

for https://bugzilla.mozilla.org/show_bug.cgi?id=1742725

Add "User Interface" setting to enable/disable "attach pasted text" feature

2021-11-24 19:12 UTC, dklawren commented
Thanks. Will take a look at this soon.

2021-11-24 22:04 UTC, dklawren requested changes

2021-11-24 22:04 UTC, dklawren commented on extensions/BugModal/web/bug_modal.js
> +    if (comment.classList.contains('allow-attach-paste')) {
I think this is maybe backwards. I think we should look for the class *not* present when presenting the confirmation dialog.

```js
if (!comment.classList.contains('allow-attach-paste')) {
```

This way if we never want to see the confirmation dialog and just always allow pasting of any size text, the user preference 'ui_allow_attach_paste' will be on. So if the js sees the class, then it skips the whole code block.

2021-11-24 22:22 UTC, arai-a commented on extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
> +  setting_descs.ui_allow_attach_paste = "Allow to attach pasted text directly"
The options I want to provide are the following 2:
  * (a) when pasting text with 50+ lines, show a dialog, if a attachment summary is written there, attach it as a file with the summary (existing behavior)
  * (b) do nothing special for pasting text with 50+ lines (new behavior)

and the option you're thinking sounds like:
  * (c) when pasting text with 50+ lines, attach it as a file, with empty summary, or template summary (new behavior)

Can I have your opinion for the option (b)?

2021-11-24 23:44 UTC, dklawren commented on extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
> +  setting_descs.ui_allow_attach_paste = "Allow to attach pasted text directly"
Sorry to cause confusion. a) and b) are truly the two choices I was thinking of. I just wanted the UI option to be descriptive that the setting only pertained to bug comments and nowhere else.

My main concern was that the JS not run if the class is present for the comment textarea. So basically if 'ui_allow_attach_paste' is set on then you would never get the dialog for any number of lines.

Of course our system default will be to 'off' which is the current behavior.

2021-11-24 23:51 UTC, arai-a commented on extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
> +  setting_descs.ui_allow_attach_paste = "Allow to attach pasted text directly"
Do you mean the option should be negated, or the effect of the class should be negated?

the option I'm thinking is that:
  * (a) == `ui_allow_attach_paste==on`
  * (b) == `ui_allow_attach_paste==off`
  * system default == (a) == `ui_allow_attach_paste==on`

if user turns the feature off, they don't get the dialog and they can paste text with any number of lines.

then, for class:
  * (a) == `allow-attach-paste` class is added to bug comment field, and the JS detects it and adds event listener for paste event
  * (b) == no class is added to bug comment field, and the JS doesn't detect the class and does nothing for paste event

2021-11-24 23:55 UTC, arai-a commented on extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
> +  setting_descs.ui_allow_attach_paste = "Allow to attach pasted text directly"
maybe "attach" word here is misleading?
my understanding is that "attach" means "convert the text into an attachment file".

2021-11-25 00:36 UTC, arai-a commented on extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
> +  setting_descs.ui_allow_attach_paste = "Allow to attach pasted text directly"
How do you think about rewording the option to
"When pasting long text in bug comments, convert it into an attachment text file"
or something along that line?

2021-11-30 10:34 UTC, arai-a commented
Reworded the option description and identifier to make it clearer what the option is for

2021-11-30 15:05 UTC, dklawren approved these changes
I like the new version better and works as expected. Thanks for the contribution! r=dkl

2021-11-30 15:06 UTC, merged