Bug 1671262 - Forbid reporters to edit the priority, severity and type fields unless they have editbugs privs
mozilla-bteam/bmo pull request #1817
Opened 2022-02-23 21:01 UTC by dklawren

2022-02-23 21:42 UTC, dklawren commented
Will fix Selenium tests before asking for review.

2022-02-28 06:46 UTC, globau requested changes

2022-02-28 06:46 UTC, globau commented on qa/t/test_bug_edit.t
> -$sel->select_ok("bug_severity", "label=blocker");
Rather than removing checks for the input field, we should check to ensure that it isn't present.

2022-03-01 05:26 UTC, globau approved these changes

2022-03-01 14:58 UTC, merged