Bug 1769284 - Show phabricator links in user_profile
mozilla-bteam/bmo pull request #1852
Opened 2022-05-13 22:14 UTC by arai-a

This adds 2 links in the `user_profile` page in new "Phabricator" section, under "Review Queue" section.
One link for user's profile page that shows recent activity: [example](https://phabricator.services.mozilla.com/p/arai/)
Other link for user's open revisions: [example](https://phabricator.services.mozilla.com/differential/?responsiblePHIDs[0]=PHID-USER-ovlr37yfp3loy53g6wgo&statuses[0]=open()&order=newest&bucket=action)

The data is retrieved during showing the user_profile page, with 2 requests, 5 seconds timeout for each.
If any error happens (including the user not found on phabricator), or if phabricator is not configured, nothing is shown.

2022-05-13 22:15 UTC, arai-a commented on Bugzilla/User.pm
> +}
I'm not sure if this is the right place.
let me know if there's better place, or if this info is already available in the template.

2022-05-14 08:36 UTC, arai-a commented
Applied some cleanup

2022-05-14 08:40 UTC, arai-a commented
This takes the option (a) in [the bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1769284#c0)

If increasing the time taken by `user_profile` page isn't acceptable, I can switch to the option (b), with redirection page added.
in that case:
  * the link will be shown regardless of whether the user has phabricator account
  * the username isn't known, so the link text will be just "Account" or something (not much problem I think)

2022-05-14 08:42 UTC, arai-a commented
Here's screenshot of this patch:
<img width="520" alt="bmo-phab-profile" src="https://user-images.githubusercontent.com/6299746/168418292-e57c1ddd-55b3-42e0-9993-4da5db437c23.png">

If the user has review request, it's shown under "Review Queue" section

2022-05-14 09:15 UTC, arai-a commented
Currently, the request to the phabricator API is done for each request.

The cache is created on the `User` instance.
So,  `target.phab_phid()` in the template requests the info and create cache, and  `target.phab_user_name()` and `target.phab_real_name()` uses the cached data,
but reloading the page triggers the API request again.

Other option is to store it in the BMO database on the initial request,
but this results in outdated cache once the the user name or the real name is modified.
To be clear, real name is only for displaying text, so not much problem (we can omit it),
but user name is used in the URL, so outdated cache is a problem.

To my understanding, the user name cannot be changed by user, but administrator can change it in case of trouble.
So, if we cache it in the BMO database, there needs to be a cache invalidation process.

2022-05-14 14:31 UTC, arai-a commented
Just realized this is very different than what the phabricator revisions view in the bug page works (and how `phabbugz` works)
I'll look into refactoring this to be dynamically generated on the client side, integrating the user/review query to `phabbugz` and communicating it after the page load.

2022-05-14 16:06 UTC, arai-a commented
Updated to utilize `PhabBugz` extension.

This patch adds `/rest/phabbugz/user/{bmo_user_id}` endpoint, that returns the following data:
```
{
  user: {
    "phid": "<User PHID>",
    "userName": "<Phabricator username>",
    "realName": "<Phabricator real name>",
    "userURL": "user page URL",
    "revisionsURL": "search page URL for the user's open revisions",
  }
}
```

If phabricator is set up on the server side, the "Phabricator" section is inserted in the `user_profile` page's reponse, with the "User" row and "Revisions" row with empty.

The `phab_user.js` script starts querying to the above endpoint, with setting "User" and "Revisions" field with "Loading..." text,
and once the response is received, those fields are replaced with links:
  * "User" : link to user's profile page that shows recent activity: [example](https://phabricator.services.mozilla.com/p/arai/)
  * "Revisions": link to user's open revisions: [example](https://phabricator.services.mozilla.com/differential/?responsiblePHIDs%5B0%5D=PHID-USER-ovlr37yfp3loy53g6wgo&statuses%5B0%5D=open()&order=newest&bucket=action)

When error happens during the request, the error is shown in the "User" row, and "Revisions" row is set to empty.

2022-05-14 17:55 UTC, arai-a commented
possible improvement would be to query `differential.revision.search` on the server side and return the length of review queue, and show it.
But so far I'm not sure how to exclude "Waiting on Other Reviewers" from the result...

2022-05-14 18:24 UTC, arai-a commented
> But so far I'm not sure how to exclude "Waiting on Other Reviewers" from the result...

I found the solution.
querying with `{"constraints": {"reviewerPHIDs": ["<phid>"], "statuses": ["needs-review"]}, "attachments": {"reviewers": true}}` returns necessary information (actually, that's `extensions/PhabBugz/lib/WebService.pm` is already doing...).
So, if that also helps, and adding more server-side request is acceptable, we can add it.

2022-05-17 17:13 UTC, dklawren requested changes
Overall everything looks great and no functionality or style issues were found. My only request is that phab_user.js be updated to use Vanilla JS instead of rely on jQuery. I realize we have quite a lot of jQuery code already in BMO but we made a choice a while back that all new code would be done using vanilla js and that we would b phasing out the use of jQuery. As time allows we will go back and refactor some of the legacy jQuery code. Let me know if this is a problem or if you need any assistance. Thanks!

2022-05-17 17:15 UTC, arai-a commented
Yeah, I just followed the other code.  I'm happy to switch to Vanilla JS :)
Will update shortly.

2022-05-17 17:18 UTC, dklawren commented
> Yeah, I just followed the other code. I'm happy to switch to Vanilla JS :) Will update shortly.

Understood. We have way more jQuery that I am comfortable with. We have some pages still using YUI2 (Yahoo's old JS framework) which is completely unsupported upstream which I have been trying to get around to porting over to plain JS.

2022-05-17 21:15 UTC, dklawren requested changes

2022-05-17 21:18 UTC, dklawren commented
> I found the solution. querying with `{"constraints": {"reviewerPHIDs": ["<phid>"], "statuses": ["needs-review"]}, "attachments": {"reviewers": true}}` returns necessary information (actually, that was `bug_revisions` in `extensions/PhabBugz/lib/WebService.pm` is already doing...). So, if that also helps, and adding more server-side request is acceptable, we can add it.

I am not sure how much value it would be to add the additional call to print the number of revisions. Users can just click through to the Phabricator page and get the information if they need it. If there is a call for it then we can add the extra as a separate bug.

2022-05-18 14:09 UTC, dklawren approved these changes
All good! r=dkl

2022-05-18 14:09 UTC, merged