Bug 1512484 - Allow to specify default version per product
mozilla-bteam/bmo pull request #1896
Opened 2022-07-21 21:26 UTC by dklawren

This was originally created by @kyoshino in #1394, but since the repo was deleted I had to create a new PR with the patch from the previous PR. So this is his code. I have looked it over and so far it all looks good and works but I will do some further testing to make sure all use cases are working.

2022-07-22 20:21 UTC, dklawren commented
A schema update only is part of the PR #1899

2022-07-22 20:23 UTC, dklawren commented
Overall this looks good as far as reviewing the code from my point of view. Maybe if someone can take a look and make sure I didnt miss anything obvious

2022-07-25 06:13 UTC, globau requested changes

2022-07-25 06:13 UTC, globau commented on Bugzilla/Product.pm
> +      = new Bugzilla::Version({name => $version, product => $invocant});
This variable should be `$ver_obj`

2022-07-25 06:13 UTC, globau commented on Bugzilla/Version.pm
> +# Copied from Milestone::update()
This comment doesn't provide any value; remove

2022-07-25 06:13 UTC, globau commented on Bugzilla/Version.pm
> +    );
I'm not sure it's correct to update bugs when the _default_ version changes.

I can see the reasoning for Milestone, as that's in the future, but the version field captures the version the bug is applicable to and it probably shouldn't be touched once it has been set by the reporter, even if it's the old default value.

2022-07-25 06:13 UTC, globau commented on Bugzilla/Version.pm
> +# Copied from Milestone::remove_from_db()
Also not valuable

2022-07-25 06:13 UTC, globau commented on template/en/default/admin/versions/confirm-delete.html.tmpl
> +    <b><blink>ALL</blink></b> of these [% terms.bugs %] will be retargeted
Don't use `<blink>`

2022-07-26 04:35 UTC, globau commented on Bugzilla/Version.pm
> +    );
I was mistaken; this is when the _version_ is updated, not when the _default version_ is updated.

2022-07-27 07:07 UTC, globau approved these changes

2022-07-27 20:21 UTC, merged