Show graph in phabricator revisions
mozilla-bteam/bmo pull request #1906
Opened 2022-07-30 17:34 UTC by arai-a

A stack of:
  * Reverse the revision order ([bug 1523847](https://bugzilla.mozilla.org/show_bug.cgi?id=1523847))
  * de-jQuery
  * some code cleanup
  * Fix "Show Abandoned Revisions" checkbox handling
  * Show graph in phabricator revisions ([bug 1782341](https://bugzilla.mozilla.org/show_bug.cgi?id=1782341))

2022-08-01 22:08 UTC, dklawren requested changes
Everything looks great and thanks for breaking it down into small commits which made it very easy to follow along with the changes being made.

Only issue I have is cosmetic. The graph itself is not rendering correctly for me (Nightly; Windows11) and not sure what needs to be tweaked. Here is a screenshot from my test setup;

![image](https://user-images.githubusercontent.com/826315/182254132-b94efc99-dcc5-4078-ae04-3375b6ca4b87.png)

2022-08-01 22:24 UTC, arai-a commented
@dklawren Can you post a screenshot with "Show Abandoned Revisions" checked? that will tell me what's going on for the 2nd row.

2022-08-01 23:27 UTC, arai-a commented
Never mind, I reproduced the issue.
I'll fix it.

2022-08-01 23:52 UTC, arai-a commented
Part 15 fixes the issue that it was using maximum count of remaining edges, and that didn't handle the case where there's only one revision after branch

Part 16 fixes the issue that when moving the parent's edge to other index, it didn't remove the straight edge.

2022-08-02 19:35 UTC, dklawren approved these changes
Looks good to me now. Thanks again for the cleanup, especially removing jQuery bits. r=dkl

![image](https://user-images.githubusercontent.com/826315/182458727-c74370e2-e090-48fe-be40-1f1e1bd6877a.png)

2022-08-02 19:35 UTC, merged