Bug 1909798 - Large dependency graphs do not work
mozilla-bteam/bmo pull request #2283
Opened 2024-07-25 21:49 UTC by dklawren

I added quotes around the bug id and summaries which should with future special characters that Mermaid treats as special.

2024-07-26 15:55 UTC, cgsheeh requested changes

2024-07-26 15:55 UTC, cgsheeh commented on showdependencygraph.cgi
> +      $link_text .= '"' . $dependson;
This seems like it's likely to break in the future... could you build up the variable to be quoted in a separate variable and then just `$link_text .= '"$dependson_text"';` instead?

2024-07-29 03:52 UTC, dklawren commented
Admittedly the add_link function is getting very complex and in the future I would like to break it apart into smaller manageable chunks.

I have pushed the latest fixes in this PR to bugzilla-dev for you to try out. Here is the original bug causing the breakage in its full, practically unreadable glory. Hopefully most dependency trees will not be this large.

2024-07-29 14:43 UTC, cgsheeh approved these changes

2024-07-29 15:46 UTC, merged