Bug 1922986 - Create script that exports BMO data as JSON suitable for import into a BigQuery instance in GCP
mozilla-bteam/bmo pull request #2370
Opened 2024-12-10 21:57 UTC by dklawren

2024-12-16 21:39 UTC, cgsheeh requested changes
Looks good to me, just a few comments/questions.

It's a lot less scary in terms of PR size once you realize there is quite a lot of repetition. You could abstract a lot of that away, but if you're pressed for time/deadlines it's okay to leave as-is.

2024-12-16 21:39 UTC, cgsheeh commented on extensions/BMO/template/en/default/hook/admin/params/editparams-current_panel.html.tmpl
> +  panel.param_descs.bmo_etl_service_account = 'THe Google service account for accessing the BMO ETL API.';
```suggestion
  panel.param_descs.bmo_etl_service_account = 'The Google service account for accessing the BMO ETL API.';
```

2024-12-16 21:39 UTC, cgsheeh commented on extensions/BMO/bin/export_bmo_etl.pl
> +# us to link two serice accounts together and give special access for applications
```suggestion
# us to link two service accounts together and give special access for applications
```

2024-12-16 21:39 UTC, cgsheeh commented on extensions/BMO/bin/export_bmo_etl.pl
> +sub store_cache {
Should we clear the cache at the end of the script?

2024-12-18 16:22 UTC, dklawren commented on docker-compose.yml
> +
bq is the correct one and bigquery is there by mistake and will be removed.

2024-12-18 17:02 UTC, dklawren commented on extensions/BMO/bin/export_bmo_etl.pl
> +        group           => (join ',', map { $_->name } @{$obj->groups_in}),
Didn't see that before. I was originally going by the schema here https://docs.google.com/spreadsheets/d/1LDrYkGxZGnktI3-Ei3fpPK2TAXjxTj7fBUjHaJ8tpBE/edit?gid=0#gid=0 which called for the group names to just be a single string. I will need to file a couple of PRs to get the schema changed but better to do so now before we have actual data going in.

2024-12-18 21:42 UTC, dklawren commented on extensions/BMO/bin/export_bmo_etl.pl
> +        group           => (join ',', map { $_->name } @{$obj->groups_in}),
https://github.com/mozilla-it/webservices-infra/pull/3627

2024-12-18 22:15 UTC, dklawren commented
I need to make some other non-related changes anyway as I realized i left out two additional requirements. 1) I need to skip sending bug data related to the 'Legal' product and 2) I need to filter the summaries, etc. for bugs that are private.

https://docs.google.com/document/d/1D-0wLQCrYXw17k_qSZiaH8djaUV-iS3qUencaj0FTtc/edit?tab=t.0#heading=h.l46cjmt1mwn6

2025-01-10 14:23 UTC, dklawren commented
I am going to make one last schema change to the BQ data so I will need to create the needed PRs in webservices-infra for this :( Once that is done, I will be able to submitted the updated code here for last review.

Context: The bugs.group field needs to be a string as I originally had it as 1) most bugs do not have more than one group anyway and 2) if there is more than one group, we just want to put the group name with the least amount of users. I missed that little detail from the schema outlined here: https://docs.google.com/spreadsheets/d/1LDrYkGxZGnktI3-Ei3fpPK2TAXjxTj7fBUjHaJ8tpBE/edit

Sorry for the extra delay.

2025-01-24 22:06 UTC, dklawren commented
Ready for hopefully final review. Optimized as much as I could. Refactored to create functions where possible. Switched to using LIMIT/OFFSET to allow for breaking down the tables that do not have a primary key into chunks instead of loading the whole table into memory (i.e. dependencies, etc.). Let me know if anything needs to be elaborated on.

2025-01-29 19:40 UTC, cgsheeh approved these changes

2025-01-29 23:03 UTC, merged